export const LOAD_ITEMS='LOAD_ITEMS';
export const ADD_ITEM='ADD_ITEM';
export const FILTER_ITEM='FILTER_ITEM';
export const ADD_SELECTION='ADD_SELECTION';
export const REMOVE_SELECTION='REMOVE_SELECTION';
export const REMOVE_ALL_SELECTION='REMOVE_ALL_SELECTION';


export const ADD_CATEGORY='ADD_CATEGORY';
export const LOAD_CATEGORIES='LOAD_CATEGORIES';

export const ADD_TO_CART='ADD_TO_CART';
export const REMOVE_ALL_FROM_CART='REMOVE_ALL_FROM_CART';
